- .github/workflows/manual-link-check-action.yml
pulled in from the autumn 2024 repo
> Add link-checking action for docs

- LICENSE
- api/to-do-db-source.json
- docs/api/task.md
- docs/tutorials/add-a-new-task.md
- postman/LICENSE
- postman/To-Do mock service tests.postman_collection.json
- postman/api/to-do-db-source.json
Change dates in docs and examples to 2025 for the new year.
> Update dates to 2025

- assignments/markdown_lyerdev.md
This pull request includes the pros and cons Markdown file for Assignment 3.4, Issue #42.
> Assignment 3.4, Issue #42

- assignments/markdown_Naem-J.md
* Create a new markdown file in the assignments folder.
* Describe the advantages and limitations of markdown.
* Provide some advice to writers new to markdown.
> feat: assignment 3.4 for Jeff Naemura

- assignments/to-do-example_rachaelallen91.md
> rachael allen - homework 5.2

- assignments/to-do-example_Naem-J.md
* Create new markdown file in assignments/ called to-do-example_Naem-J.
* Add a command and response example pair for cURL and Postman interfaces.
* Add the author and short descriptions of the examples.
* Fixes #55
> feat: add curl and postman examples in new file assignments/to-do-example_Naem-J.md

- assignments/my-api-example_juliebro.md
- assignments/to-do-example_juliebro.md
I'm not sure why the other file is along for the ride. I must have changed it. But I don't know how to remove it from the pull request.
Fixes #48
Fixes #64
> Trying to make a pull request just for my-api-example_juliebro.md

- assignments/my-api-example_rachaelallen91.md
> homework 5.3

- assignments/code-example_Davejurgens.md
- assignments/markdown_Davejurgens.md
- assignments/my-api-example_Davejurgens.md
Hi Bob,
Please accept the pull request for assignment 5.2.
Regards,
Dave
Fixes: #33
Fixes: #50 
Fixes: #66
> Assignment 5.2 Code examples from cURL and Postman

- assignments/my-api-example_cristinalom.md
New file: my-api-example_cristinalom.md
> Feature5.3

- assignments/my-api-example_Naem-J.md
* Add my-api-example_Naem-J.md.
* Add code request and response examples from new JSON file created on my local computer related to Tillamook creamery products.
> feat: add a .md file with code examples of a new api

- assignments/my-api-example_Marmelodov.md
> Assignment 5.3 my-api-example_Marmelodov.md

- assignments/my-api-example_KusumaKrish15.md
- assignments/to-do-example_KusumaKrish15.md
Add code example to fix Issue #51 (cURL and Postman)
Also includes code to fix issue #67
> Assignment 5.2 - Code examples from cURL and Postman

- assignments/my-api-example_allenaavila.md
- assignments/to-do-example_allenaavila.md
Hello, I'm submitting my changes for Assignment 5.2 by opening a pull request from my feature branch for issue #47. 
Resolves #47
Resolves #63 
Please let me know if you have any feedback on the code examples I created from my to-do service. 
Thank you in advance.
> To-do-example_allenaavila.md to fix Issue #47

- docs/index.md
- docs/overviews/to-do-overview_allenaavila.md
Creates to-do-overview_allenaavila.md.
Adds a new and improved to-do overview topic.
Updated index with link.
> Add a new overview topic to fix #103

- docs/index.md
- docs/overviews/to-do-overview_KusumaKrish15.md
For assignment 6.1, I've created a new overview topic with the file name `to-do-overview_KusumaKrish15.md` in the docs\overviews directory.
Link to the new Overview topic:
https://github.com/KusumaKrish15/to-do-service-sp25/blob/Feature-2/docs/overviews/to-do-overview_KusumaKrish15.md
> Feature 2 - KusumaKrish15 to create a new Overview topic for the To-Do Service - Fixes Issue #107

- docs/tutorials.md
- docs/tutorials/get-task-by-id.md
* Add get-task-by-id.md to /tutorials to provide a tutorial for retrieving task details by ID number.
* Add a link in tutorials.md to the new file.
> Add get-task-by-id.md to tutorials and add link in tutorials.md to fix issue #132

- docs/tutorials.md
- docs/tutorials/get-user-by-user-id.md
Creates Get user by user ID topic to fix issue #124
Adds Get user by user ID topic to Tutorials
> Add a new GET user tutorial topic to fix issue #124

- docs/api/user.md
- docs/api/users-post-users.md
Create post-users.md file for a new reference topic. 
Update user.md to add link to new reference topic.
> Add a new POST users reference topic to fix #140

- docs/api/task.md
- docs/api/tasks-add-a-task.md
Also updated index.md to add a link to this topic.
> created a new reference topic about POST /tasks to fix #141

- docs/index.md
- docs/overviews/to-do-overview_cristinalom.md
Add a new overview topic to fix issue #108
> Feature6.1

- docs/index.md
- docs/overviews/to-do-overview_Naem-J.md
* Create a new overview markdown file in /overviews.
* Add link to overviews/to-do-overview_Naem_J.md in index.md.
> Add a new overview file for Jeff Naemura and add link in index.md to fix issue #111

- docs/index.md
- docs/overviews/to-do-overview_lyerdev.md
Create to-do-overview_lyerdev.md and update index.md
> Assignment 6.1 - Issue #115

- docs/api/task.md
- docs/api/tasks-delete-id.md
Creates tasks-delete-id topic and resolves Assignment 6.3 & Issue #151.
> Assignment 6.3 and Issue #151

- docs/index.md
- docs/overviews/to-do-overview_rgmejiagroup.md
Closes #113
This adds a new overview markdown file to the docs/overviews directory as required in Assignment 6.1.
> Add overview topic for To-Do API (Assignment 6.1)

- docs/index.md
- docs/tutorials.md
- docs/tutorials/update-a-task.md
> Assignment6 2

- postman/to-do-example_cristinalom.md
Add a new code example topic to fix issue #52
> Feature5.2

- to-do-example_cjmoreno094.md
> Assignment 5.2 to fix issue #54

- docs/overviews/to-do-overview_tihsle.md
created a new Overview topic for the To-Do Service to fix issue #105
> created a new Overview topic for the To-Do Service to fix issue #105

- docs/index.md
- docs/tutorials/get-users.md
> create get-users.md for homework 6.2

- docs/tutorials/user-id.md
Hi Bob,
Please accept my pull request for Assignment 6.2.
Regards,
Dave
> Assignment 6.2

- docs/api/update_user-by-id.md
> create a new reference topic about PATCH /users/{userID} to fix issue #142

- docs/api/update_task.md
Adding an API Reference topic for the PATCH /tasks/{taskId} operation.
> Feature4 - API Reference for PATCH /tasks/{taskId} operation for Issue #143
